[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
hashbrown = "0.14.3"
lazy_static = "1.4"
cargo-watch = "8.5.2"
